# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks 
use_frameworks!

target 'hw2-MRT' do
 # Pods for hw2-MRT
	pod 'ObjectMapper', '~> 1.2'
end
